atributos_input = [['_current_error_color', [0, 0, 0, 0]], 
 ['_current_hint_text_color', [0.0, 0.0, 0.0, 0.38]], 
 ['_current_line_color', [0.24705882352941178, 0.3176470588235294, 0.7098039215686275, 1.0]], 
 ['_current_right_lbl_color', [0, 0, 0, 0]], 
 ['_cursor_blink', False], 
 ['_cursor_visual_height', 17], 
 ['_cursor_visual_pos', [36, 35]], 
 ['_editable', True], 
 ['_fill_color', [0, 0, 0, 0]], 
 ['_hint_lbl_font_size', 16.0], 
 ['_hint_text', 'potência ativa'], 
 ['_hint_text_lines', []], 
 ['_hint_y', 38.0], 
 ['_ime_composition', ''], 
 ['_ime_cursor', None], 
 ['_keyboard', None], 
 ['_line_blank_space_left_point', 0], 
 ['_line_blank_space_right_point', 0], 
 ['_line_width', 0], 
 ['_lines', ['48 W']], 
 ['_text_len_error', False], 
 ['active_line', True], 
 ['allow_copy', True], 
 ['auto_indent', False], 
 ['background_active', 'atlas://data/images/defaulttheme/textinput_active'], 
 ['background_color', [1, 1, 1, 1]], 
 ['background_disabled_normal', 'atlas://data/images/defaulttheme/textinput_disabled'], 
 ['background_normal', 'atlas://data/images/defaulttheme/textinput'], 
 ['base_direction', None], 
 ['border', [4, 4, 4, 4]], 
 ['center', [50.0, 25.5]], 
 ['center_x', 50.0], 
 ['center_y', 25.5], 
 ['children', []], 
 ['cls', []], 
 ['color_mode', 'primary'], 
 ['current_hint_text_color', [0.8980392156862745, 0.8980392156862745, 0.8980392156862745, 1.0]], 
 ['cursor', (4, 0)], 
 ['cursor_blink', True], 
 ['cursor_col', 4], 
 ['cursor_color', [1, 0, 0, 1]], 
 ['cursor_pos', (36, 35.0)], 
 ['cursor_row', 0], 
 ['cursor_width', 1.0], 
 ['device_ios', False], 
 ['disabled', False], 
 ['disabled_foreground_color', [0, 0, 0, 0.5]], 
 ['error', False], 
 ['error_color', [0.8352941176470589, 0.0, 0.0, 1.0]], 
 ['fill_color', [0, 0, 0, 0]], 
 ['focus', False], 
 ['focus_next', None], 
 ['focus_previous', None], 
 ['focused', False], 
 ['font_context', None], 
 ['font_family', None], 
 ['font_name', 'Roboto'], 
 ['font_name_helper_text', 'Roboto'], 
 ['font_name_hint_text', 'Roboto'], 
 ['font_name_max_length', 'Roboto'], 
 ['font_size', 16.0], 
 ['foreground_color', [0.0, 0.0, 0.0, 0.87]], 
 ['halign', 'auto'], 
 ['handle_image_left', 'atlas://data/images/defaulttheme/selector_left'], 
 ['handle_image_middle', 'atlas://data/images/defaulttheme/selector_middle'], 
 ['handle_image_right', 'atlas://data/images/defaulttheme/selector_right'], 
 ['height', 51.0], 
 ['helper_text', 'This field is required'], 
 ['helper_text_mode', 'none'], 
 ['hint_text', 'potência ativa'], 
 ['hint_text_color', [0.5, 0.5, 0.5, 1.0]], 
 ['icon_right', ''], 
 ['icon_right_color', [0, 0, 0, 1]], 
 ['ids', {}], ['input_filter', None], 
 ['input_type', 'text'], 
 ['is_focusable', True], 
 ['keyboard', None], 
 ['keyboard_mode', 'auto'], 
 ['keyboard_suggestions', True], 
 ['line_anim', True], 
 ['line_color_focus', [0.24705882352941178, 0.3176470588235294, 0.7098039215686275, 1.0]], 
 ['line_color_normal', [0.0, 0.0, 0.0, 0.12]], 
 ['line_height', 17], 
 ['line_spacing', 0], 
 ['max_height', 0], 
 ['max_text_length', None], 
 ['minimum_height', 43.0],
 ['mode', 'line'], 
 ['multiline', False], 
 ['opacity', 1.0], 
 ['opposite_colors', False], 
 ['padding', [0, 16.0, 0, 10.0]], 
 ['padding_x', [0, 0]], 
 ['padding_y', [0, 0]], 
 ['parent', None], 
 ['password', False], 
 ['password_mask', '*'], 
 ['pos', [0, 0]], 
 ['pos_hint', {}], 
 ['radius', [10, 10, 0, 0]], 
 ['readonly', False], 
 ['replace_crlf', True], 
 ['required', False], 
 ['right', 100], 
 ['scroll_x', 0], 
 ['scroll_y', 0], 
 ['selection_color', [0.1843, 0.6549, 0.8313, 0.5]], 
 ['selection_from', None], 
 ['selection_text', ''], 
 ['selection_to', None], 
 ['size', [100, 51.0]], 
 ['size_hint', [1, None]], 
 ['size_hint_max', [None, None]], 
 ['size_hint_max_x', None], 
 ['size_hint_max_y', None], 
 ['size_hint_min', [None, None]], 
 ['size_hint_min_x', None], 
 ['size_hint_min_y', None], 
 ['size_hint_x', 1], 
 ['size_hint_y', None], 
 ['suggestion_text', ''], 
 ['tab_width', 4], 
 ['text', '48 W'], 
 ['text_color', None], 
 ['text_language', None], 
 ['text_validate_unfocus', True], 
 ['theme_cls', '<kivymd.theming.ThemeManager object at 0x0000023D9BB28EB0>'], 
 ['top', 51.0], ['unfocus_on_touch', True], 
 ['use_bubble', False], 
 ['use_handles', False], 
 ['widget_style', 'android'], 
 ['width', 100], 
 ['write_tab', True], 
 ['x', 0], 
 ['y', 0], 
 ['bold', False]]
























